
spring:
  datasource:
    generate-unique-name: false
#    driverClassName: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/main_db
#    username: artiom
#    password: admin
    url: jdbc:mysql://localhost:3306/my_database
    username: artiom
    password: admin
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
    main:
      web-development-type: servlet
      application:
    name: crm-demo
server:
  port: 8080
logging:
  level:
    org.thymeleaf: DEBUG

security:
  jwt:
    token:
      secret-key: my-secret-key-is-1C4E0A2D3B5F2D784E6A1B423D6F247D
